#!/usr/bin/env python3
"""Regenerate wiki/_index.md, _backlinks.json and _grades.json from the articles.

These are projections of the articles, not state. They were previously rebuilt
as a remembered manual step, and the step was forgotten: one repo shipped an
_index.md listing 27 of 51 articles with the ops/ and integrations/ sections
missing entirely.

That is not cosmetic. absorb_runner puts _index.md in the prompt and the system
prompt permits wikilinks ONLY to titles in it, so an article the index cannot see
gets written again under a near-identical name. It produced "Backend New API"
beside "backend_new API", two "(Package)"-suffixed twins, and four separate MCP
Server articles.

Call rebuild() at the end of every absorb batch. Never hand-edit the outputs.

    python3 build_index.py --wiki path/to/wiki [--title "Name"]
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import vocab  # noqa: E402

# Section order for _index.md, from vocab.py. Types not listed there still
# appear, under a trailing Unclassified section, so a retired or unknown type
# can never be silently dropped from the index.
TYPE_ORDER = vocab.TYPE_ORDER

FM_RE = re.compile(r"^---\n(.*?)\n---", re.S)
WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")
GRADE_RE = re.compile(r"\[(verified|code|doc|conflict|gap)[:\]]")


def read_article(path: Path) -> dict | None:
    """Title, type, one-line summary and outbound links. None if unparseable."""
    text = path.read_text(encoding="utf-8", errors="replace")
    m = FM_RE.match(text)
    if not m:
        return None
    fm, body = m.group(1), text[m.end():]
    field = lambda k: (re.search(rf"^{k}:\s*(.+)$", fm, re.M) or [None, ""])[1].strip().strip('"')
    title = field("title")
    if not title:
        return None
    # The summary is the article's first real sentence, truncated. Cheaper and
    # more honest than asking the model for a separate one-liner it would drift from.
    first = next((ln.strip() for ln in body.splitlines()
                  if ln.strip() and not ln.startswith(("#", "|", "-", "`"))), "")
    summary = re.sub(r"\[[^\]]*\]|\(.*?\)|[`*]", "", first).strip()
    return {
        "title": title,
        "type": field("type") or "unknown",
        "path": str(path),
        "summary": (summary[:70].rsplit(" ", 1)[0] + "…") if len(summary) > 70 else summary,
        "links": set(WIKILINK_RE.findall(fm + body)),
        "grades": [g for g in GRADE_RE.findall(body)],
        "hub": field("hub") == "true",
    }


def collect(wiki: Path) -> list[dict]:
    out = []
    for p in sorted(wiki.rglob("*.md")):
        if p.name.startswith("_"):
            continue
        a = read_article(p)
        if a:
            a["path"] = str(p.relative_to(wiki.parent)).replace("\\", "/")
            out.append(a)
    return out


def duplicate_titles(articles: list[dict]) -> dict[str, list[str]]:
    """Titles that collide once case and the '(Package)'-style suffix are removed.

    Every real duplicate observed in the wild was one of these two shapes, and both
    are invisible to an exact-match check.
    """
    norm = lambda t: re.sub(r"\s*\([^)]*\)\s*$", "", t).lower().replace("_", " ").strip()
    by_norm = defaultdict(list)
    for a in articles:
        by_norm[norm(a["title"])].append(a["title"])
    return {k: v for k, v in by_norm.items() if len(set(v)) > 1}


def render_index(articles: list[dict], title: str) -> str:
    hubs = [a for a in articles if a.get("hub")]
    by_type = defaultdict(list)
    for a in articles:
        if not a.get("hub"):
            by_type[a["type"]].append(a)

    lines = [f"# {title}", "",
             "Generated by pipeline/build_index.py. Do not hand-edit — "
             "it is rebuilt after every absorb batch.", ""]
    if hubs:
        lines += ["## Topics", ""]
        for a in sorted(hubs, key=lambda x: x["title"]):
            lines.append(f"- [[{a['title']}]]" + (f" — {a['summary']}" if a["summary"] else ""))
        lines.append("")
    seen = set()
    for key, heading in TYPE_ORDER:
        if not by_type.get(key):
            continue
        seen.add(key)
        lines += [f"## {heading}", ""]
        for a in sorted(by_type[key], key=lambda x: x["title"]):
            lines.append(f"- [[{a['title']}]]" + (f" — {a['summary']}" if a["summary"] else ""))
        lines.append("")
    leftover = sorted(k for k in by_type if k not in seen)
    if leftover:
        lines += ["## Unclassified", "",
                  "_Types with no section in TYPE_ORDER — reconcile with "
                  "docs/wiki-taxonomy.md._", ""]
        for key in leftover:
            for a in sorted(by_type[key], key=lambda x: x["title"]):
                lines.append(f"- [[{a['title']}]] — `type: {key}`")
        lines.append("")

    counts = ", ".join(f"{k} {len(v)}" for k, v in sorted(by_type.items()))
    if hubs:
        counts = f"topics {len(hubs)}" + (f", {counts}" if counts else "")
    lines += ["## Counts", "", f"{len(articles)} articles — {counts}", ""]
    return "\n".join(lines)


def rebuild(wiki: Path, title: str = "Wiki Index") -> dict:
    """Rewrite the three derived files. Returns a summary for the caller/log."""
    articles = collect(wiki)
    titles = {a["title"] for a in articles}

    backlinks = {a["title"]: {"path": a["path"], "backlinks_from": []} for a in articles}
    for a in articles:
        for target in a["links"]:
            # A link to a title that does not exist is a broken link, not a new
            # node — recording it would make _backlinks.json assert articles
            # that were never written.
            if target in backlinks and target != a["title"]:
                backlinks[target]["backlinks_from"].append(a["title"])
    for v in backlinks.values():
        v["backlinks_from"].sort()

    grades = {a["title"]: {g: a["grades"].count(g) for g in set(a["grades"])}
              for a in articles}

    (wiki / "_index.md").write_text(render_index(articles, title), encoding="utf-8")
    (wiki / "_backlinks.json").write_text(json.dumps(backlinks, indent=1) + "\n", encoding="utf-8")
    (wiki / "_grades.json").write_text(json.dumps(grades, indent=1) + "\n", encoding="utf-8")

    dupes = duplicate_titles(articles)
    dangling = sorted({t for a in articles for t in a["links"]} - titles)
    return {"articles": len(articles), "duplicate_titles": dupes, "dangling_links": dangling}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--wiki", type=Path, required=True)
    ap.add_argument("--title", default="Wiki Index")
    a = ap.parse_args()
    if not a.wiki.is_dir():
        return print(f"no such wiki dir: {a.wiki}", file=sys.stderr) or 2

    r = rebuild(a.wiki, a.title)
    print(f"indexed {r['articles']} articles")
    for norm, variants in r["duplicate_titles"].items():
        print(f"  duplicate: {sorted(set(variants))}", file=sys.stderr)
    if r["dangling_links"]:
        print(f"  dangling wikilinks: {r['dangling_links'][:8]}", file=sys.stderr)
    # Duplicates are a finding, not a crash: the index still rebuilds, and the
    # caller decides whether to block. Exit 1 so CI can gate on it.
    return 1 if r["duplicate_titles"] else 0


if __name__ == "__main__":
    sys.exit(main())
